# Generated by Django 5.2.17 on 2026-09-29 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('turma', models.CharField(max_length=50)),
                ('curso', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('editora', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('quantidade_total', models.PositiveIntegerField(default=1)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=1)),
                ('localizacao', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['titulo', 'autor'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade_disponivel__lte', models.F('quantidade_total'))), name='disponivel_ate_total')],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.localdate)),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido')], default='ATIVO', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='biblioteca.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='biblioteca.livro')),
            ],
            options={
                'ordering': ['-data_emprestimo', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('data_devolucao__isnull', True), ('status', 'ATIVO')), models.Q(('data_devolucao__isnull', False), ('status', 'DEVOLVIDO')), _connector='OR'), name='status_conforme_devolucao')],
            },
        ),
    ]
