# Generated by Django 5.2.17 on 2026-08-17 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=150)),
                ('editora', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('quantidade_total', models.PositiveIntegerField(default=1)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=1)),
                ('localizacao', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(blank=True, help_text='Durante o protótipo pode ficar vazio; em produção, associe cada livro a uma escola.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='escolas.escola')),
            ],
            options={
                'ordering': ['titulo', 'autor'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade_disponivel__lte', models.F('quantidade_total'))), name='livro_disponivel_nao_supera_total')],
            },
        ),
    ]
