# Generated by Django 5.2.17 on 2026-08-17 03:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField(default=django.utils.timezone.localdate)),
                ('data_prevista_devolucao', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ALUGADO', 'Alugado'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='ALUGADO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_aluguel', '-id'],
            },
        ),
    ]
