# Generated by Django 5.2.17 on 2026-08-17 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimos', '0001_initial'),
        ('livros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='aluno',
            field=models.ForeignKey(limit_choices_to={'tipo': 'ALUNO'}, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='livros.livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
